<template>
    <form @submit="onSubmit" class="mb-3">
        <div class="mb-3">
            <label for="" class="form-label">Task</label>
            <input v-model="text" type="text" class="form-control" id="" aria-describedby="">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Day & Time</label>
            <input v-model="day" type="text" class="form-control" id="">
        </div>
        <div class="mb-3 form-check">
            <input v-model="reminder" type="checkbox" class="form-check-input" id="">
            <label class="form-check-label" for="">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
</template>

<script>
    export default {
        name: 'AddTask',
        data() {
            return {
                text: '',
                day: '',
                reminder: false
            }
        },
        methods: {
            onSubmit(e){
                e.preventDefault();

                if (!this.text) {
                    alert('Please add a text');
                    return
                }

                const newTask = { 
                    /*
                    id: , # The id will be auto generated by JSON Server */
                    text: this.text,
                    day: this.day,
                    reminder: this.reminder,
                }

                this.$emit('add-task', newTask);

                this.text = '',
                this.day = '',
                this.reminder = false
            }
        }
    }
</script>